version: '2'
services:
  renren-admin:
    image: renren/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
    links:
      - mysql
  renren-api:
    image: renren/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev
    links:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=huangzelin
    volumes:
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/conf:/etc/mysql/conf
      - /root/mysql/log:/logs